include:
  - .cnb/workflows/deploy-docs.yml
  - .cnb/workflows/ci-check.yml
  - .cnb/workflows/auto-tag.yml
  - .cnb/workflows/release-prepare.yml
  - .cnb/workflows/pre-release-check.yml
  - .cnb/workflows/release.yml
  - .cnb/workflows/build-image.yml
  - .cnb/workflows/automerge.yml

$:
  vscode:
    - runner:
        cpus: 32
      docker:
        image: docker.cnb.cool/wwvo/dev-env/rust:latest
      services:
        - vscode
        - docker
